apiVersion: apps/v1
kind: Deployment
metadata:
  name: "acme-a3"
spec:
  selector:
    matchLabels:
      app: "acme-a3"
  replicas: {{ .Values.replicacount }}
  template:
    metadata:
      labels:
        app: "acme-a3"
    spec:
      containers:
        - image: {{ .Values.image }}
          name: "acme-a3"
          env:
            - name: DB_HOST
              value: {{ .Values.dbhost }}
            - name: DB_USER
              value: {{ .Values.dbusername }}
            - name: DB_PASS
              value: {{ .Values.dbpass }}
            - name: "PORT"
              value: "80"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
